# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3617fb66195fe77b4ee083a1ca76fa851a6fb16b0adc3a5f6514485ac841c63ecbe6af4f44af48c66ba9a1c5f399ff937e92fb99dbc4be2167a4e2476f762055

test:
  secret_key_base: cc78585133769a9cf30173f11cc433604089abbd76052f69c3d801f3bd5a33652faf624f085a65b88f394edf8c954001dce6dea0c0bcb19dd66ff4767e482f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
